export const GP_PLAYER_ACTIONS = {
    INITIALIZE_MODULE: '[Player] GP_INITIALIZE_MODULE',
    INITIALIZE_SUCCESS: '[Player] GP_INITIALIZE_SUCCESS',
    INITIALIZE_FAILURE: '[Player] GP_INITIALIZE_FAILURE',
    SET_PLAY_STATE: "[Player] SET_PLAY_STATE",
    SWITCH_PLAY_STATE: '[Player] GP_SWITCH_PLAY',
    SWITCH_PLAY_STATE_SUCCESS: '[Player] GP_SWITCH_PLAY_STATE_SUCCESS',
    SWITCH_PLAY_STATE_FAILURE: '[Player] GP_SWITCH_PLAY_STATE_FAILURE',
    TRIGGER_PREVIOUS: '[Player] GP_TRIGGER_PREVIOUS',
    TRIGGER_NEXT: '[Player] TRIGGER_NEXT',
    SET_VOLUME: '[Player] GP_VOLUME_CHANGE',
    VOLUME_CHANGE_SUCCESS: '[Player] GP_VOLUME_CHANGE_SUCCESS',
    VOLUME_CHANGE_FAILURE: '[Player] GP_VOLUME_CHANGE_FAILURE'
};
